### ISSUE TITLE
wnlsf and dtlsf

### ISSUE THREAD

**Issue by kasmf** [osqzss/gps-sdr-sim#116]
do u help me about wnlsf = 1929%256 and dtlsf = 18 ? why not the year others instead of 1929 and dllsf instead of 18 and also what is the module of 256

**Comment by Honky103** [comment]
Wnlsf=1929 is not the year. It is the week number. Dtlsf is the leap seconds. It refers to the time difference betwern gps time and utc time. As of week number 1929, the leap seconds is 18. I.e gps time is 18 seconds behind utc time. Module 256 is because the week number is represented as a 8 bit number in subframe 4

**Comment by kasmf** [comment]
thank you Honky
